django-spider/home_spider/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
#    path('update/', include('homelink.urls')),
#    path('', include('homelink.urls')),
    path('', include('showdeals.urls')),
]

django-spider/homelink/urls.py
from django.urls import path
from . import views

app_name = 'homelink'

urlpatterns = [
    path('', views.house_index, name='house_index'),
    path('fetch/', views.house_fetch, name='house_fetch'),
    path('spider/', views.house_spider, name='house_spider'),
]

django-spider/homelink/models.py
from django.db import models

# Create your models here.

class HouseInfo(models.Model):
    title = models.CharField(max_length=256, verbose_name='标题')
    house = models.CharField(max_length=20, verbose_name='小区')
    bedroom = models.CharField(max_length=20, verbose_name='房厅')
    area = models.CharField(max_length=20, verbose_name='面积')
    direction = models.CharField(max_length=20, verbose_name='朝向')
    floor = models.CharField(max_length=60, verbose_name='朝向')
    year = models.CharField(max_length=10, verbose_name='年份')
    location = models.CharField(max_length=10, verbose_name='位置')
    total_price = models.IntegerField(verbose_name='总结(万元)')
    unit_price = models.IntegerField(verbose_name='单价(元/平方米)')
    image_url = models.CharField(max_length=512, verbose_name='图片')
    add_date = models.DateTimeField(auto_now_add=True, verbose_name="创建日期")
    mod_date = models.DateTimeField(auto_now=True, verbose_name="修改日期")
    house_url = models.CharField(max_length=512, verbose_name='house_url')

    def __str__(self):
        return "{}-{}-{}".format(self.house,self.bedroom, self.total_price)

    class Meta:
        verbose_name = "二手房"

django-spider/homelink/forms.py
from django import forms

DISTRICT_CHOICES = (('pudong', '浦东'), ('minhang', '闵行'), ('xuhui', '徐汇'))
PRICE_CHOICES = (('p3', '300-400万'), ('p4', '400-500万'), ('p5', '500-800万'))
BEDROOM_CHOICES = (('l2', '二室'), ('l3', '三室'))

class HouseChoiceForm(forms.Form):
    district = forms.CharField(label="区域", widget=forms.RadioSelect(choices=DISTRICT_CHOICES))
    price = forms.CharField(label="价格", widget=forms.RadioSelect(choices=PRICE_CHOICES))
    bedroom = forms.CharField(label="庭室", widget=forms.RadioSelect(choices=BEDROOM_CHOICES))

django-spider/homelink/views.py
from django.shortcuts import render
from .models import HouseInfo
from .forms import HouseChoiceForm
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect

from fake_useragent import UserAgent
import requests
from bs4 import BeautifulSoup
import re

# list all houses result
def house_index(request):
    form = HouseChoiceForm()
    house_list = HouseInfo.objects.all().order_by('-add_date')
    if house_list:
        paginator = Paginator(house_list, 20)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)

        return render(request, 'homelink/index.html',
                      {'page_obj': page_obj, 'paginator': paginator,
                       'is_paginated': True, 'form': form, })
    else:
        return render(request, 'homelink/index.html', {'form': form, })

# fetch all houses result
def house_fetch(request):
    form = HouseChoiceForm()
    return render(request, 'homelink/fetch.html', {'form': form, })
'''
    house_list = HouseInfo.objects.all().order_by('-add_date')
    if house_list:
        paginator = Paginator(house_list, 20)
        page = request.GET.get('page')
        page_obj = paginator.get_page(page)

        return render(request, 'homelink/fetch.html',
                      {'page_obj': page_obj, 'paginator': paginator,
                       'is_paginated': True, 'form': form, })
    else:
        return render(request, 'homelink/fetch.html', {'form': form, })
'''

# invoke spider
def house_spider(request):
    if request.method == 'POST':
        # get form
        form = HouseChoiceForm(request.POST)
        if form.is_valid():
            district = form.cleaned_data.get('district')
            price = form.cleaned_data.get('price')
            bedroom = form.cleaned_data.get('bedroom')
            url = 'https://sh.lianjia.com/ershoufang/{}/{}{}'.format(
                district, price, bedroom)

            # invoke spider function
            home_spider = HomeLinkSpider(url)
            home_spider.get_max_page()
            home_spider.parse_page()
            home_spider.save_data_to_model()
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

# the actual spider invoker
class HomeLinkSpider(object):
    def __init__(self, url):
        self.ua = UserAgent()
        self.headers = {"User-Agent": self.ua.random}
        self.data = list()
        self.url = url

    def get_max_page(self):       # get total Pages of the result
        response = requests.get(self.url, headers=self.headers)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            a = soup.select('div[class="page-box house-lst-page-box"]')
            max_page = eval(a[0].attrs["page-data"])["totalPage"]  # 使用eval是字符串转化为字典格式
            return max_page
        else:
            print("请求失败 status:{}".format(response.status_code))
            return None

    def parse_page(self):           # loop each page "sellListContent" for record list "li"
        max_page = self.get_max_page()
        for i in range(1, max_page + 1):
            url = "{}pg{}/".format(self.url, i)
            response = requests.get(url, headers=self.headers)
            soup = BeautifulSoup(response.text, 'html.parser')
            ul = soup.find_all("ul", class_="sellListContent")
            li_list = ul[0].select("li")
            for li in li_list:
                detail = dict()

                detail['house_url'] = li.select('div[class="title"]')[0].find('a').attrs['href']

                detail['title'] = li.select('div[class="title"]')[0].get_text()
                
                # new house_info:          2室2厅 | 71.02平米 | 南 北 | 简装 | 高楼层(共6层) | 1996年建 | 板楼
                house_info = li.select('div[class="houseInfo"]')[0].get_text()
                house_info_list = house_info.split(" | ")

                detail['bedroom'] = house_info_list[0]
                detail['area'] = house_info_list[1]
                detail['direction'] = house_info_list[2]

                #提取楼层，年份和板块: 南新东园 - 外高桥
                position_info = li.select('div[class="positionInfo"]')[0].get_text().split(' - ')

                floor_pattern = re.compile(r'.+\)')
                match1 = re.search(floor_pattern, house_info_list[4])  # 从字符串任意位置匹配

                if match1:
                    detail['floor'] = match1.group()
                else:
                    detail['floor'] = "未知"

                year_pattern = re.compile(r'\d{4}')
                match2 = re.search(year_pattern, house_info_list[5])  # 从字符串任意位置匹配

                if match2:
                    detail['year'] = match2.group()
                else:
                    detail['year'] = "未知"

                detail['house'] = position_info[0]
                detail['location'] = position_info[1]

                # 650万，匹配650
                price_pattern = re.compile(r'\d+')
                total_price = li.select('div[class="totalPrice"]')[0].get_text()
                detail['total_price'] = re.search(price_pattern, total_price).group()

                # 单价64182元/平米， 匹配64182
                unit_price = li.select('div[class="unitPrice"]')[0].get_text()
                detail['unit_price'] = re.search(price_pattern, unit_price).group()
                self.data.append(detail)

                # image URL
                images = li.select("img", {"class": "lj-lazy"})
                for image in images:
                    if image['class'] == ['lj-lazy']:
                        detail['image_url'] = image['data-original']

    def save_data_to_model(self):
        for item in self.data:
            new_item = HouseInfo()
            new_item.title = item['title']
            new_item.house = item['house']
            new_item.bedroom = item['bedroom']
            new_item.area = item['area']
            new_item.direction = item['direction']
            new_item.floor = item['floor']
            new_item.year = item['year']
            new_item.location = item['location']
            new_item.total_price = item['total_price']
            new_item.unit_price = item['unit_price']
            new_item.image_url = item['image_url']
            new_item.house_url = item['house_url']
            new_item.save()

django-spider/homelink/templates/homelink/base.html
{% load static %}

<html lang="en">
<head>
<title>{% block title %} Snap Hot Deal{% endblock %} </title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        ul li {
        display:inline;
        list-style-type:none;
        }
    </style>
</head>

<body>
 <!-- Page content of course! -->
<main>
    <div class="container">
    {% block content %}
  {% if error_message %}<p><strong>{{ error_message}}</strong></p>{% endif %}
  {% endblock %}
        </div>
</main>


<footer class="footer">
  {% block footer %}Copyright 2020@SnapHotDeals{% endblock %}
</footer>
<!--End of Footer-->

<!-- Bootstrap core JavaScript
================================================== -->

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

django-spider/homelink/templates/homelink/fetch.html
{% extends "homelink/base.html" %}

{% block title %}Update Records{% endblock %}

{% block content %}

<h3>Scrape ShangHai Second Hand Info</h3>
<form method="POST" class="form-horizontal" role='form' action="{% url 'homelink:house_spider' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="form-group">
    <div class="col-md-12">
      <button type="submit" class="btn btn-primary form-control">Start Ccraping</button>
    </div>
  </div>
</form>

{% endblock %}

django-spider/homelink/templates/homelink/index.html
{% extends "homelink/base.html" %}

{% block title %}Display Records{% endblock %}

{% block content %}
<!---
<h3>爬取上海链家二手房信息</h3>
<form method="POST" class="form-horizontal" role='form' action="{% url 'homelink:house_spider' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="form-group">
    <div class="col-md-12">
      <button type="submit" class="btn btn-primary form-control">开始爬取</button>
    </div>
  </div>
</form>
--->

{% if page_obj %}
<h3>show latest result</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>图片</th>
      <th>标题</th>
      <th>小区</th>
      <th>房厅</th>
      <th>面积</th>
      <th>年份</th>
      <th>板块</th>
      <th>总价(万)</th>
      <th>单价(元/平方米)</th>
      <th>链接</th>
    </tr>
  </thead>
  <tbody>
    {% for house in page_obj %}
    <tr>
      <td>
        <img src="{{ house.image_url  }}">
      </td>
      <td>
      {{ house.title }}
      </td>
      <td>
        {{ house.house }}
      </td>
      <td>
        {{ house.bedroom }}
      </td>
      <td>
        {{ house.area }}
      </td>
      <td>
        {{ house.year }}
      </td>
      <td>
        {{ house.location }}
      </td>
      <td>
        {{ house.total_price }}
      </td>
      <td>
        {{ house.unit_price }}
      </td>
      <td>
        <a href="{{ house.house_url }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" target="_blank">Link</a>
      </td>
      
      {% endfor %}
    </tr>
  </tbody>
</table>

{% else %}
<p>尚无二手房信息。</p>
{% endif %}


{# 注释: 下面代码实现分页 #}
{% if is_paginated %}
<ul class="pagination">
  {% if page_obj.has_previous %}
  <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
  {% else %}
  <li class="page-item disabled"><span class="page-link">Previous</span></li>
  {% endif %}

  {% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
  <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
  <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
  {% else %}
  <li class="page-item disabled"><span class="page-link">Next</span></li>
  {% endif %}
</ul>

{% endif %}

{% endblock %}